apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stayops-chroma-pvc
  labels:
    app: stayops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
